### ISSUE TITLE
Fatal errors when used with Jetpack -- incorrect number of parameters used with filter

### ISSUE THREAD

**Issue by jeherve** [bluehost/endurance-wp-module-data#9]
#4 appears to be causing some Fatals at the moment, on sites with the Jetpack plugin installed, since https://github.com/bluehost/bluehost-wordpress-plugin/pull/38 added the `wp-module-data` as a new dependency of the plugin.

```
Error Details
=============
An error of type E_ERROR was caused in line 35 of the file /home4/hometoo1/public_html/wp-content/plugins/bluehost-wordpress-plugin/vendor/endurance/wp-module-data/src/Listeners/Jetpack.php. Error message: Uncaught ArgumentCountError: Too few arguments to function Endurance\WP\Module\Data\Listeners\Jetpack::connected(), 1 passed in /home4/hometoo1/public_html/wp-includes/class-wp-hook.php on line 287 and exactly 3 expected in /home4/hometoo1/public_html/wp-content/plugins/bluehost-wordpress-plugin/vendor/endurance/wp-module-data/src/Listeners/Jetpack.php:35
Stack trace:
#0 /home4/hometoo1/public_html/wp-includes/class-wp-hook.php(287): Endurance\WP\Module\Data\Listeners\Jetpack->connected(Array)
#1 /home4/hometoo1/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(”, Array)
#2 /home4/hometoo1/public_html/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#3 /home4/hometoo1/public_html/wp-content/plugins/jetpack/class.jetpack.php(3442): do_action(‘jetpack_log_ent…’, Array)
#4 /home4/hometoo1/public_html/wp-content/plugins/jetpack/class.jetpack.php(4202): Jetpack::log(‘register’)
#5 /home4/hometoo1/public_html/wp-content/plugins/jetpack/_inc/lib/admin-pages/class.jetpack-admin-page.php(
```

The `jetpack_log_entry` filter used in `src/Listeners/Jetpack.php` only accepts one parameter:
https://github.com/Automattic/jetpack/blob/bb27f0b0997b624ba5db5d2f0d45c36f900bd95b/class.jetpack.php#L3427-L3442
You won't be able to pass it 3 parameters I'm afraid.

cc @earnjam

**Bluehost Plugin Version:**
* Version: 2.2.2

This was reported here:
https://wordpress.org/support/topic/critical-error-on-jetpack-setup/

**Comment by earnjam** [comment]
Hmm, not sure how I got 3 parameters there. Thanks @jeherve we'll get it fixed up.

**Comment by earnjam** [comment]
Ah, I see now. I meant to change to the `jetpack_site_registered` hook.
